language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to run tests
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install enum34; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then pip install typing; fi
script: nosetests
