language: python
matrix:
  include:
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    - python: '3.9'
script:
  - pip install .
  - cd tests && python3 -m pytest
before_deploy:
  - cd ..
deploy:
  skip_cleanup: true
  provider: pypi
  user: __token__
  password:
    secure: EyJ+iqh4EzCxkfsyeM3jNgCH0k5LQgmG+A1RYSWQO6fvO4XPrZLhebEyIluc+q6lUPVUFJF0Ml0Hln2/Xh4y9LbGBhXOKXbMmrsH2W/d1Nh7mjWnKxWbufOXamgYVH4wPPSIdnsSQVbB3+1OXHOOlPtx4sA+HTUCXs3QY+moPpZC8TflI8yexXItORYyDV3xRr2ISSQw4BZQBnpa/DEY5ema+nyUC8DK7F0TMlImoCxDfpJvkT00VMWrAtkMZUchWbJtvVQdGoLGW+GT8oX+dbCD4WTfI4pRVUIzY2eGje/ePR0j30M/A1/hpcxenaROPD/Q5XI1rwNPMLn76JqNmvUfHzOl2vFZEPkONhxs2lBdASiQyvDWwumn89RgdjURC3QQy3Rw3lJWF3CTGoi0uHr4ojIOL6MuXei7fyFcCkFaoJ5+EjgZSqCCHWlGAmAIBpZzXtj0XDgsvFeSkVOjVu7Rrqg+D5VRW6UO4+MmVxit9IxtKhsb+Zrh7EQ1GcCOHGX7D6Tc05rOB/3B52SEgb5dfjLlrRmWrO3bmZO6xW2gRdoxzDTgVEA23WjYQO5zJKMSko5+o9imhh6+S2wDQddgyf97uG2D3aTxbmnhiADPZzCyZpSYLja1d+IHn0n0Gn/nldqcwpdSM0QJIy8LSu9ouDPika57oyhDW0Wl9aw=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
